### ISSUE TITLE
Clicking Go nothing happens

### ISSUE THREAD

**Issue by iamkim17** [OnePanelOrg/LandingPage#1]
Hi, Clicking the Go button in the Demo reader doesn't do anything, what I'm missing at? I put a https://tcbscans.me/chapters/7770/my-hero-academia-chapter-428 but nothing happen

**Comment by thanzeelhassan** [comment]
> Hi, Clicking the Go button in the Demo reader doesn't do anything, what I'm missing at? I put a https://tcbscans.me/chapters/7770/my-hero-academia-chapter-428 but nothing happen

+1. Same issue

**Comment by vincenzocassaro** [comment]
thanks for the heads up, it should be fixed now via https://github.com/OnePanelOrg/OnePanelNext/pull/8
